version: '2'

services:
  db:
    build: ./MySql51
    environment:
      - MYSQL_ROOT_PASSWORD=hunter2
      - MYSQL_DATABASE=mftutor
      - MYSQL_USER=mftutor
      - MYSQL_PASSWORD=hunter2
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db-data:
